name: Web

on:
  pull_request:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./web

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.16.0
          cache: npm
          cache-dependency-path: web/package-lock.json
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.16.0
          cache: npm
          cache-dependency-path: web/package-lock.json
      - run: npm ci
      - run: npm run test
